// Add entries to this array for new projects — portals spawn automatically
export const PROJECTS = [
  {
    id: 'blind-auction',
    name: 'Blind Auction',
    description: 'A real-time blind auction platform where users bid without seeing others\' bids. Features live countdowns, Socket.IO-powered updates, and a sleek bidding interface.',
    techStack: ['React', 'Express', 'Socket.IO'],
    github: 'https://github.com/ELPYi/gamba',
    liveUrl: '#',
    planetColor: 0x2277aa,
    atmosColor: 0x66ccff,
    accentColor: 0x00ffff,
    hasRing: true,
    scale: 1.4,
    position: { x: -120, y: 10, z: -160 },
  },
  {
    id: 'meltdown-clowns',
    name: 'Meltdown Clowns',
    description: 'A chaotic multiplayer party game featuring clown-themed mayhem. Players compete in absurd mini-games with physics-based antics.',
    techStack: ['JavaScript', 'Canvas API', 'Node.js'],
    github: 'https://github.com/ELPYi',
    liveUrl: '#',
    planetColor: 0xcc5533,
    atmosColor: 0xff8855,
    accentColor: 0xff00ff,
    hasRing: false,
    scale: 0.7,
    position: { x: 80, y: -8, z: -250 },
  },
  {
    id: 'scattergories',
    name: 'Scattergories',
    description: 'A digital adaptation of the classic word game. Timed rounds, category-based scoring, and multiplayer lobbies for competitive wordplay.',
    techStack: ['React', 'Firebase', 'CSS Animations'],
    github: 'https://github.com/ELPYi',
    liveUrl: '#',
    planetColor: 0x44886a,
    atmosColor: 0x88ddaa,
    accentColor: 0xff6ec7,
    hasRing: false,
    scale: 1.0,
    position: { x: 140, y: 15, z: -400 },
  },
  {
    id: 'tictactoe',
    name: 'Tic Tac Toe',
    description: 'A polished Tic Tac Toe game with an unbeatable AI opponent powered by the minimax algorithm. Features smooth animations and score tracking.',
    techStack: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/ELPYi',
    liveUrl: '#',
    planetColor: 0xccaa55,
    atmosColor: 0xffdd88,
    accentColor: 0x39ff14,
    hasRing: true,
    scale: 1.8,
    position: { x: -60, y: -10, z: -550 },
  },
];
